import React, { useEffect, useState } from "react";
import Chair from "./Chair";
import axios from "axios";
import { Toaster, toast } from 'react-hot-toast';
function Chairs({ musorId, setValasztottDB, setValasztottHelyek, valasztottHelyek, musor, valasztottDB, username, film, setMusor }) {

  const [szekek, setSzekek] = useState([]);
  const [show, setShow] = useState(false);


  useEffect(() => {
    setTimeout(() => {
      setShow(true);
    }, 500)
  })

  useEffect(() => {
    fetchChairs()
  }, [valasztottHelyek]);

  const fetchChairs = async () => {
    await axios
      .get(`http://localhost:3002/szekek/${musorId}`, {
        headers: {
          accessToken: localStorage.getItem("accessToken"),
        },
      })
      .then((response) => {
        if (response.data.error) {
          toast.error("Hiba történt!");
        } else {
          setSzekek(response.data);
        }
      });
  }

  const handleSubmit = () => {
    axios.post(`http://localhost:3002/kosar/jegyfoglalas`, { adatok: { username: username, musorId: musorId, valasztottHelyek: valasztottHelyek } }).then((response) => {
      if(response.data.error){
        toast.error("Hiba történt!");
      }else {
        toast.success(`Sikeres jegyfoglalás!`);
        setMusor({ticketsLeft: response.data.maradtJegyek});
        setValasztottDB(0);
        setValasztottHelyek([]);
      }
    })
}


  return (
    <>
    {show && 
    <>
      <div className="chair-container">
      <Toaster position="middle-right" reverseOrder={false} />
        <div className="ticket-booking-descriptions">
              <p className="vanticket">Elérhető jegyek: {musor.ticketsLeft}</p>
              <p className="vhd">Választott helyek darabszáma: {valasztottDB}</p>
              </div>
              <div className="chairs-template">
                <div className="chairs-lefoglalt">
                 <i className="fa-solid fa-couch foglalt"></i>
                <p className="plefoglalt">Lefoglalt szék</p>
             </div>
             <div className="chairs-valasztott">
             <i className="fa-solid fa-couch selected"></i>
             <p className="pvalasztott">Választott szék</p>
             </div>
             <div className="chairs-szabad">
             <i className="fa-solid fa-couch"></i>
             <p>Foglalható szék</p>
             </div>
              </div>
              <div className="chair-seat-container">
        <div className="first-row">
          <div className="first-box-container">

            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[0]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[1]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[6]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[3]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[4]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[5]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[2]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[7]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[8]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[9]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[10]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[11]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[12]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[13]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[14]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[15]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[16]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[17]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[18]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[19]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[20]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[21]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[22]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[23]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[24]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[25]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[26]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[27]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[28]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[29]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[30]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[31]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[32]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[33]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[34]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[35]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[36]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[37]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[38]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[39]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[40]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[41]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[42]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[43]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[44]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[45]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[46]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[47]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[48]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[49]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[50]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[51]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[52]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[53]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[54]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[55]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[56]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[57]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[58]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[59]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[60]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[61]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[62]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[63]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[64]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[65]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[66]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[67]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[68]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[69]}
              setValasztottDB={setValasztottDB}
            />
          </div>
        </div>
        <div className="second-row">
          <div className="first-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[70]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[71]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[72]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[73]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[74]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[75]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[76]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="second-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[77]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[78]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[79]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[80]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[81]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[82]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[83]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="second-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[84]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[85]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[86]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[87]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[88]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[89]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[90]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="second-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[91]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[92]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[93]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[94]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[95]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[96]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[97]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="second-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[98]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[99]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[100]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[101]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[102]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[103]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[104]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="second-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[105]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[106]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[107]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[108]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[109]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[110]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[111]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="second-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[112]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[113]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[114]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[115]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[116]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[117]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[118]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="second-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[119]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[120]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[121]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[122]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[123]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[124]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[125]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="second-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[126]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[127]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[128]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[129]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[130]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[131]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[132]}
              setValasztottDB={setValasztottDB}
            />
          </div>
          <div className="second-box-container">
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[133]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[134]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[135]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[136]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[137]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[138]}
              setValasztottDB={setValasztottDB}
            />
            <Chair
              valasztottHelyek={valasztottHelyek}
              setValasztottHelyek={setValasztottHelyek}
              szekAdatok={szekek[139]}
              setValasztottDB={setValasztottDB}
            />
          </div>
        </div>
        </div>
        {valasztottDB >= 1 && (
                <button onClick={handleSubmit} className="ticket-btn">
                  <i class="fa-solid fa-ticket"></i>Jegyfoglalás
                </button>
              )}
      </div>
      </>
      }
    </>
  );
}

export default Chairs;
